spring:
  application:
    name: hello-spring-cloud-service-admin
server:
  port: 8762
#启动两台service的时候先点击Edit Configuration
#找到本工程启动WebAdminRibbonApplication，
#  Modify Options -> 选中 Allow multiple instances
#  旧版本：弹出Run/Debug Configuration对话框，勾选Allow parallel run 或者 取消勾选Single instance only
#修改这里上面的server.port为8763后再启动一个8763的实例就有了两台service一个8762一个8763
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/