spring:
  application:
    name: hello-spring-cloud-web-admin-feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

#-----------------------介绍springcloud中所有需要被追踪的项目（除了dependencies除外，包括eurekaserver）
  zipkin:
    base-url: http://localhost:9411
#  yml文件中都要增加zipkin server的地址即可 spring.zipkin.base-url:http://localhost:9411
#-----------------------介绍springcloud中所有需要被追踪的项目（除了dependencies除外，包括eurekaserver）

server:
  port: 8765
#feign自带netflix的hystrix熔断器，此处开启
feign:
  hystrix:
    enabled: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

